name = "Create: Ultimate Selection"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0d7f9d8c0bafd6530fa2eb8999efa2257d6ece487342f68aa322da1acdcad2da"

[versions]
forge = "47.4.2"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1"]
