name = "Create: Ultimate Selection"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e46fcb5f968a6bd12e76b57f6b0c9c9232075d6cb2b188943823581c6204ed05"

[versions]
forge = "47.4.2"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1"]
