name = "Create: Ultimate Selection"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2d85826424fa793fe96fe42d9aae3b94f06c0bf9a974eec534a46d38f725701c"

[versions]
forge = "47.4.2"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1"]
